### ISSUE TITLE
slow speed of URL-specified displacement map.

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/insarmaps#37]
For the command beow it does three things: (1) the regular display, (2) the display of the displacement time series, and (3) the temporal zoom into the time period of interest. This takes literally 59 seconds on my laptop. Can't we skip the first two steps?

```
https://insarmaps.miami.edu/start/19.4289/-155.6005/10.2598?flyToDatasetCenter=false&startDataset=S1_IW12_087_0527_0531_20180902_XXXXXXXX&pointID=645557&minScale=-1&maxScale=1&startDate=20201003&endDate=20201208&colorscale=displacement
```

**Comment by stackTom** [comment]
Closing this for now. On my computers, it takes around 30-40 seconds for the first recoloring, and 5-10 for subsequent re-colorings after updating to the latest mapbox (as seen here: https://github.com/geodesymiami/insarmaps/issues/53#issuecomment-1200326805). So now, it gets faster on subsequent re-colorings rather than slower (old version of mapbox had a significant memory leak).
